/*
 * Copyright 2017 Sairaorg209
 */

/**
 *
 * @author Sairaorg209
 */
public class Frame0 extends javax.swing.JFrame {

    /**
     * Creates new form Frame0
     */
    private Frame1 F1;
    private Frame2 F2;
    private static int sum;
    
    
    public Frame0() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currentWalletButton = new javax.swing.JButton();
        metroWalletButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        plasticPouchButton = new javax.swing.JButton();
        bankOfIndiaButton = new javax.swing.JButton();
        oldTornWalletButton = new javax.swing.JButton();
        hajmolaContainersButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO MYALLWMNGR: EXPENSE WALLET");

        currentWalletButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        currentWalletButton.setText("CURRENT WALLET");
        currentWalletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentWalletButtonActionPerformed(evt);
            }
        });

        metroWalletButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        metroWalletButton.setText("METRO WALLET");
        metroWalletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroWalletButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        plasticPouchButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        plasticPouchButton.setText("PLASTIC POUCH WALLET");
        plasticPouchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plasticPouchButtonActionPerformed(evt);
            }
        });

        bankOfIndiaButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        bankOfIndiaButton.setText("BANK OF INDIA POUCH");
        bankOfIndiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankOfIndiaButtonActionPerformed(evt);
            }
        });

        oldTornWalletButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        oldTornWalletButton.setText("OLD TORN WALLET");
        oldTornWalletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldTornWalletButtonActionPerformed(evt);
            }
        });

        hajmolaContainersButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        hajmolaContainersButton.setText("HAJMOLA CONTAINERS");
        hajmolaContainersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hajmolaContainersButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oldTornWalletButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bankOfIndiaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plasticPouchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(metroWalletButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(currentWalletButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hajmolaContainersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentWalletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(metroWalletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(plasticPouchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(bankOfIndiaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oldTornWalletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hajmolaContainersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentWalletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentWalletButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Current Wallet");
    }//GEN-LAST:event_currentWalletButtonActionPerformed

    private void metroWalletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroWalletButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Metro Wallet");
    }//GEN-LAST:event_metroWalletButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F1.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void plasticPouchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plasticPouchButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Plastic Pouch");
    }//GEN-LAST:event_plasticPouchButtonActionPerformed

    private void bankOfIndiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankOfIndiaButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Bank of India pouch");
    }//GEN-LAST:event_bankOfIndiaButtonActionPerformed

    private void oldTornWalletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldTornWalletButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Old Torn Wallet");
    }//GEN-LAST:event_oldTornWalletButtonActionPerformed

    private void hajmolaContainersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hajmolaContainersButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        F2.invokeF2(F1, sum, "Hajmola Containers");
    }//GEN-LAST:event_hajmolaContainersButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

  
     /**
     * @param args the command line arguments
     */
    public void invokeF0(Frame1 f1, Frame2 f2,int s) {
        F1=f1;
        F2=f2;
        sum=s;
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton bankOfIndiaButton;
    private javax.swing.JButton currentWalletButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton hajmolaContainersButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton metroWalletButton;
    private javax.swing.JButton oldTornWalletButton;
    private javax.swing.JButton plasticPouchButton;
    // End of variables declaration//GEN-END:variables
}
